import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import React from 'react'
import styles from '../styles/Home.module.css'

const Home : React.FC = () =>  {
  const router = useRouter();
  const handleClick = () => {
    router.push("/products");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleClick}>Order Products</button>
    </div>
  )
}

export default Home;